version: 0.2

phases: 
    build:
        commands:
            - echo "Build block"
            - ls
            - echo "Running tests to check if "Sudip" present in index.html file"
            - grep "SUDIP" index.html
    post_build:
        commands:
            - echo "Post build phase"
artifacts:
    type: zip
    files:
        - '**/*'
   
